name: Update File List

on:
  push:
    paths:
      - 'downloads/**'
      - 'scripts/**'

jobs:
  generate-list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Generate File List
        run: |
          node scripts/generate-list.js
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add downloads-data.json
          git commit -m "自动更新文件列表"
          git push